-- PROCEDURE: public.sp_create_new_users()

-- DROP PROCEDURE IF EXISTS public.sp_create_new_users();

CREATE OR REPLACE PROCEDURE public.sp_create_new_users(
	)
LANGUAGE 'sql'
AS $BODY$
INSERT INTO SPL_USERS (PLAYER_NAME, CHECKED_TIMESTAMP)
SELECT PLAYER_NAME,
		'1900-01-01 00:00:00'
FROM
(SELECT PLAYER_1_NAME AS PLAYER_NAME FROM SPL_GAMES
 UNION ALL
 SELECT PLAYER_2_NAME AS PLAYER_NAME FROM SPL_GAMES
) as tmp
WHERE tmp.PLAYER_NAME NOT IN (SELECT PLAYER_NAME FROM SPL_USERS)
GROUP BY tmp.PLAYER_NAME;
$BODY$;
ALTER PROCEDURE public.sp_create_new_users()
    OWNER TO postgres;
